# Generated by Django 5.2.14 on 2026-05-07 12:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_id', models.CharField(db_index=True, max_length=128)),
                ('public_key_fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('jwt_jti', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('refresh_jti', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('agent_version', models.CharField(blank=True, default='', max_length=32)),
                ('os_kind', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')], max_length=16)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=255)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='assets.asset')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agents_agent',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('scope', models.CharField(default='enroll', max_length=64)),
                ('max_uses', models.PositiveSmallIntegerField(default=1)),
                ('used_count', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('used_for_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agents.agent')),
            ],
            options={
                'db_table': 'agents_enrollment_token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentCommand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('rescan', 'Rescan'), ('update_config', 'Update config'), ('revoke', 'Revoke')], max_length=32)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('dispatched', 'Dispatched'), ('acked', 'Acknowledged'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='queued', max_length=16)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='agents.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agents_command',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'status'], name='cmd_agent_status_idx')],
            },
        ),
    ]
