# Generated by Django 5.2.14 on 2026-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='enrolled_by',
        ),
        migrations.AlterField(
            model_name='agent',
            name='machine_id',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name='EnrollmentToken',
        ),
    ]
