# Generated by Django 5.2.14 on 2026-05-07 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_scan_id', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ingest_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('agent_version', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescan_command', 'Rescan command'), ('manual', 'Manual'), ('enroll', 'Enrollment')], default='scheduled', max_length=32)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('diff_from_previous', models.JSONField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to='agents.agent')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to='assets.asset')),
            ],
            options={
                'db_table': 'scanning_scan_session',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['asset', '-received_at'], name='scan_asset_recent_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('agent__isnull', False)), fields=('agent', 'client_scan_id'), name='uniq_agent_client_scan_id')],
            },
        ),
    ]
