# Generated by Django 5.2.14 on 2026-05-07 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'assets_asset_type',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('fqdn', models.CharField(blank=True, default='', max_length=512)),
                ('serial_number', models.CharField(blank=True, default='', max_length=128)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=128)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('os_name', models.CharField(blank=True, default='', max_length=64)),
                ('os_version', models.CharField(blank=True, default='', max_length=64)),
                ('os_build', models.CharField(blank=True, default='', max_length=64)),
                ('os_arch', models.CharField(blank=True, default='', max_length=32)),
                ('cpu_model', models.CharField(blank=True, default='', max_length=255)),
                ('cpu_cores', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ram_total_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('motherboard', models.CharField(blank=True, default='', max_length=255)),
                ('gpu', models.CharField(blank=True, default='', max_length=255)),
                ('current_user_login', models.CharField(blank=True, default='', max_length=128)),
                ('last_logged_user', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('agent_version', models.CharField(blank=True, default='', max_length=32)),
                ('is_manual', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
                ('asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assettype')),
            ],
            options={
                'db_table': 'assets_asset',
                'ordering': ['-last_seen_at', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='AssetOwnerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField()),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_history', to='assets.asset')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets_owner_history',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(max_length=128)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('free_bytes', models.BigIntegerField(blank=True, null=True)),
                ('fs_type', models.CharField(blank=True, default='', max_length=32)),
                ('mount_point', models.CharField(blank=True, default='', max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='assets.asset')),
            ],
            options={
                'db_table': 'assets_disk',
            },
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('mac_address', models.CharField(max_length=64)),
                ('ip_addresses', models.JSONField(blank=True, default=list)),
                ('is_primary', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_interfaces', to='assets.asset')),
            ],
            options={
                'db_table': 'assets_nic',
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['hostname'], name='asset_hostname_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['-last_seen_at'], name='asset_last_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('serial_number',), name='uniq_asset_serial_when_present'),
        ),
        migrations.AddConstraint(
            model_name='networkinterface',
            constraint=models.UniqueConstraint(fields=('asset', 'mac_address'), name='uniq_asset_mac'),
        ),
    ]
