# Generated by Django 5.2.14 on 2026-07-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_bios_release_date_asset_bios_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='current_owner',
        ),
        migrations.RemoveField(
            model_name='assetownerhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='asset',
            name='current_owner_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='assetownerhistory',
            name='owner_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
