# Generated by Django 5.2.16 on 2026-07-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_current_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='bios_release_date',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='asset',
            name='bios_version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cpu_arch',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os_build',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os_display_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os_edition',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
