import hashlib
import json

from django.db import models

from apps.core.models import UUIDPKModel


class ScanSession(UUIDPKModel):
    """One scan event from an agent.

    Stores the full payload as JSONB for flexibility, plus indexed scalar
    columns for the hot path. Idempotent on (agent, client_scan_id).
    """

    class Source(models.TextChoices):
        SCHEDULED = "scheduled", "Scheduled"
        RESCAN_COMMAND = "rescan_command", "Rescan command"
        MANUAL = "manual", "Manual"
        ENROLL = "enroll", "Enrollment"

    agent = models.ForeignKey(
        "agents.Agent", on_delete=models.CASCADE,
        null=True, blank=True, related_name="scan_sessions",
    )
    asset = models.ForeignKey(
        "assets.Asset", on_delete=models.CASCADE,
        related_name="scan_sessions",
    )

    # Idempotency key generated by the agent (ULID/UUID)
    client_scan_id = models.CharField(max_length=64, db_index=True)

    started_at = models.DateTimeField()
    finished_at = models.DateTimeField()
    received_at = models.DateTimeField(auto_now_add=True, db_index=True)
    ingest_duration_ms = models.PositiveIntegerField(null=True, blank=True)

    agent_version = models.CharField(max_length=32, blank=True, default="")
    source = models.CharField(
        max_length=32, choices=Source.choices,
        default=Source.SCHEDULED,
    )

    payload = models.JSONField()
    payload_hash = models.CharField(max_length=64, db_index=True)

    diff_from_previous = models.JSONField(null=True, blank=True)

    class Meta:
        db_table = "scanning_scan_session"
        ordering = ["-received_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["agent", "client_scan_id"],
                condition=models.Q(agent__isnull=False),
                name="uniq_agent_client_scan_id",
            ),
        ]
        indexes = [
            models.Index(fields=["asset", "-received_at"], name="scan_asset_recent_idx"),
        ]

    @staticmethod
    def compute_payload_hash(payload: dict) -> str:
        canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()
